-- AlterTable
ALTER TABLE `dossiers` MODIFY `statut_numerisation` ENUM('EN_ATTENTE', 'EN_COURS', 'A_VALIDER', 'TERMINE', 'REJETE') NOT NULL DEFAULT 'EN_ATTENTE',
    MODIFY `statut_indexation` ENUM('EN_ATTENTE', 'EN_COURS', 'A_VALIDER', 'TERMINE', 'REJETE') NOT NULL DEFAULT 'EN_ATTENTE',
    MODIFY `statut_archivage` ENUM('EN_ATTENTE', 'EN_COURS', 'A_VALIDER', 'TERMINE', 'REJETE') NOT NULL DEFAULT 'EN_ATTENTE';
