/**
 * Import des 201 communes officielles de Côte d'Ivoire (loi n°2014-451),
 * source : Direction Générale de la Décentralisation et du Développement
 * Local (DGDDL, Ministère de l'Intérieur — http://dgddl.gouv.ci/commune.php,
 * page « LISTE DES 201 COMMUNES »). Noms tels que publiés par la source
 * officielle (sans accent — l'encodage d'origine du site les omet déjà),
 * volontairement non « corrigés » pour rester fidèle à la source vérifiée
 * plutôt que d'inventer une orthographe. Extraction automatisée du HTML de
 * la source (pas de saisie manuelle).
 *
 * Idempotent (upsert par code) — peut être relancé sans dupliquer.
 * Usage : DATABASE_URL=... npx tsx scripts/import-communes-ci.ts
 */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const COMMUNES: Array<{ code: string; nom: string }> = [
  { code: "CI-001", nom: "Abengourou" },
  { code: "CI-002", nom: "Abobo" },
  { code: "CI-003", nom: "Aboisso" },
  { code: "CI-004", nom: "Adiake" },
  { code: "CI-005", nom: "Adjame" },
  { code: "CI-006", nom: "Adzope" },
  { code: "CI-007", nom: "Affery" },
  { code: "CI-008", nom: "Agboville" },
  { code: "CI-009", nom: "Agnibilekro" },
  { code: "CI-010", nom: "Agou" },
  { code: "CI-011", nom: "Akoupe" },
  { code: "CI-012", nom: "Alepe" },
  { code: "CI-013", nom: "Anoumaba" },
  { code: "CI-014", nom: "Anyama" },
  { code: "CI-015", nom: "Arrah" },
  { code: "CI-016", nom: "Assinie-Mafia" },
  { code: "CI-017", nom: "Assuefry" },
  { code: "CI-018", nom: "Attecoube" },
  { code: "CI-019", nom: "Attiegouakro" },
  { code: "CI-020", nom: "Ayame" },
  { code: "CI-021", nom: "Azaguie" },
  { code: "CI-022", nom: "Bako" },
  { code: "CI-023", nom: "Bangolo" },
  { code: "CI-024", nom: "Bassawa" },
  { code: "CI-025", nom: "Bediala" },
  { code: "CI-026", nom: "Beoumi" },
  { code: "CI-027", nom: "Bettie" },
  { code: "CI-028", nom: "Biankouma" },
  { code: "CI-029", nom: "Bingerville" },
  { code: "CI-030", nom: "Binhouye" },
  { code: "CI-031", nom: "Blolequin" },
  { code: "CI-032", nom: "Bocanda" },
  { code: "CI-033", nom: "Bodokro" },
  { code: "CI-034", nom: "Bondoukou" },
  { code: "CI-035", nom: "Bongouanou" },
  { code: "CI-036", nom: "Bonieredougou" },
  { code: "CI-037", nom: "Bonon" },
  { code: "CI-038", nom: "Bonoua" },
  { code: "CI-039", nom: "Booko" },
  { code: "CI-040", nom: "Borotou" },
  { code: "CI-041", nom: "Botro" },
  { code: "CI-042", nom: "Bouafle" },
  { code: "CI-043", nom: "Bouake" },
  { code: "CI-044", nom: "Bouna" },
  { code: "CI-045", nom: "Boundiali" },
  { code: "CI-046", nom: "Brobo" },
  { code: "CI-047", nom: "Buyo" },
  { code: "CI-048", nom: "Cocody" },
  { code: "CI-049", nom: "Dabakala" },
  { code: "CI-050", nom: "Dabou" },
  { code: "CI-051", nom: "Daloa" },
  { code: "CI-052", nom: "Danane" },
  { code: "CI-053", nom: "Daoukro" },
  { code: "CI-054", nom: "Diabo" },
  { code: "CI-055", nom: "Dianra" },
  { code: "CI-056", nom: "Diawala" },
  { code: "CI-057", nom: "Didievi" },
  { code: "CI-058", nom: "Diegonefla" },
  { code: "CI-059", nom: "Dikodougou" },
  { code: "CI-060", nom: "Dimbokro" },
  { code: "CI-061", nom: "Dioulatiedougou" },
  { code: "CI-062", nom: "Divo" },
  { code: "CI-063", nom: "Djebonoua" },
  { code: "CI-064", nom: "Djekanou" },
  { code: "CI-065", nom: "Djibrosso" },
  { code: "CI-066", nom: "Doropo" },
  { code: "CI-067", nom: "Dualla" },
  { code: "CI-068", nom: "Duekoue" },
  { code: "CI-069", nom: "Ettrokro" },
  { code: "CI-070", nom: "Facobly" },
  { code: "CI-071", nom: "Ferkessedougou" },
  { code: "CI-072", nom: "Foumbolo" },
  { code: "CI-073", nom: "Fresco" },
  { code: "CI-074", nom: "Fronan" },
  { code: "CI-075", nom: "Gagnoa" },
  { code: "CI-076", nom: "Gbeleban" },
  { code: "CI-077", nom: "Gboguhe" },
  { code: "CI-078", nom: "Gbon" },
  { code: "CI-079", nom: "Gbonne" },
  { code: "CI-080", nom: "Gohitafla" },
  { code: "CI-081", nom: "Goulia" },
  { code: "CI-082", nom: "Grabo" },
  { code: "CI-083", nom: "Grand Lahou" },
  { code: "CI-084", nom: "Grand Zattry" },
  { code: "CI-085", nom: "Grand-Bassam" },
  { code: "CI-086", nom: "Grand-Bereby" },
  { code: "CI-087", nom: "Gueyo" },
  { code: "CI-088", nom: "Guiberoua" },
  { code: "CI-089", nom: "Guiembe" },
  { code: "CI-090", nom: "Guiglo" },
  { code: "CI-091", nom: "Guinteguela" },
  { code: "CI-092", nom: "Guitry" },
  { code: "CI-093", nom: "Hire" },
  { code: "CI-094", nom: "Issia" },
  { code: "CI-095", nom: "Jacqueville" },
  { code: "CI-096", nom: "Kanakono" },
  { code: "CI-097", nom: "Kani" },
  { code: "CI-098", nom: "Kaniasso" },
  { code: "CI-099", nom: "Karakoro" },
  { code: "CI-100", nom: "Kassere" },
  { code: "CI-101", nom: "Katiola" },
  { code: "CI-102", nom: "Kokoumbo" },
  { code: "CI-103", nom: "Kolia" },
  { code: "CI-104", nom: "Komborodougou" },
  { code: "CI-105", nom: "Kong" },
  { code: "CI-106", nom: "Kongasso" },
  { code: "CI-107", nom: "Koonan" },
  { code: "CI-108", nom: "Korhogo" },
  { code: "CI-109", nom: "Koro" },
  { code: "CI-110", nom: "Kouassi Dattekro" },
  { code: "CI-111", nom: "Kouassi Kouassikro" },
  { code: "CI-112", nom: "Kouibly" },
  { code: "CI-113", nom: "Koumassi" },
  { code: "CI-114", nom: "Koumbala" },
  { code: "CI-115", nom: "Koun Fao" },
  { code: "CI-116", nom: "Kounahiri" },
  { code: "CI-117", nom: "Kouto" },
  { code: "CI-118", nom: "Lakota" },
  { code: "CI-119", nom: "Logouale" },
  { code: "CI-120", nom: "M'Bahiakro" },
  { code: "CI-121", nom: "M'Batto" },
  { code: "CI-122", nom: "M'Bengue" },
  { code: "CI-123", nom: "Madinani" },
  { code: "CI-124", nom: "Mafere" },
  { code: "CI-125", nom: "Man" },
  { code: "CI-126", nom: "Mankono" },
  { code: "CI-127", nom: "Marcory" },
  { code: "CI-128", nom: "Massala" },
  { code: "CI-129", nom: "Mayo" },
  { code: "CI-130", nom: "Meagui" },
  { code: "CI-131", nom: "Minignan" },
  { code: "CI-132", nom: "Morondo" },
  { code: "CI-133", nom: "N'Douci" },
  { code: "CI-134", nom: "Napie" },
  { code: "CI-135", nom: "Nassian" },
  { code: "CI-136", nom: "Niable" },
  { code: "CI-137", nom: "Niakaramadougou" },
  { code: "CI-138", nom: "Nielle" },
  { code: "CI-139", nom: "Niofoin" },
  { code: "CI-140", nom: "Odienne" },
  { code: "CI-141", nom: "Ouangolodougou" },
  { code: "CI-142", nom: "Ouaninou" },
  { code: "CI-143", nom: "Ouelle" },
  { code: "CI-144", nom: "Oume" },
  { code: "CI-145", nom: "Ouragahio" },
  { code: "CI-146", nom: "Plateau" },
  { code: "CI-147", nom: "Port Bouet" },
  { code: "CI-148", nom: "Prikro" },
  { code: "CI-149", nom: "Rubino" },
  { code: "CI-150", nom: "Saioua" },
  { code: "CI-151", nom: "Sakassou" },
  { code: "CI-152", nom: "Samatiguila" },
  { code: "CI-153", nom: "San-Pedro" },
  { code: "CI-154", nom: "Sandegue" },
  { code: "CI-155", nom: "Sangouine" },
  { code: "CI-156", nom: "Sarhala" },
  { code: "CI-157", nom: "Sassandra" },
  { code: "CI-158", nom: "Satama Sokoro" },
  { code: "CI-159", nom: "Satama Sokoura" },
  { code: "CI-160", nom: "Seguela" },
  { code: "CI-161", nom: "Seguelon" },
  { code: "CI-162", nom: "Seydougou" },
  { code: "CI-163", nom: "Sifie" },
  { code: "CI-164", nom: "Sikensi" },
  { code: "CI-165", nom: "Sinematiali" },
  { code: "CI-166", nom: "Sinfra" },
  { code: "CI-167", nom: "Sipilou" },
  { code: "CI-168", nom: "Sirasso" },
  { code: "CI-169", nom: "Songon" },
  { code: "CI-170", nom: "Soubre" },
  { code: "CI-171", nom: "Taabo" },
  { code: "CI-172", nom: "Tabou" },
  { code: "CI-173", nom: "Tafire" },
  { code: "CI-174", nom: "Tai" },
  { code: "CI-175", nom: "Tanda" },
  { code: "CI-176", nom: "Tehini" },
  { code: "CI-177", nom: "Tengrela" },
  { code: "CI-178", nom: "Tiapoum" },
  { code: "CI-179", nom: "Tiassale" },
  { code: "CI-180", nom: "Tie N'Diekro" },
  { code: "CI-181", nom: "Tiebissou" },
  { code: "CI-182", nom: "Tieme" },
  { code: "CI-183", nom: "Tiemelekro" },
  { code: "CI-184", nom: "Tieningboue" },
  { code: "CI-185", nom: "Tienko" },
  { code: "CI-186", nom: "Tioroniaradougou" },
  { code: "CI-187", nom: "Tortiya" },
  { code: "CI-188", nom: "Touba" },
  { code: "CI-189", nom: "Toulepleu" },
  { code: "CI-190", nom: "Toumodi" },
  { code: "CI-191", nom: "Transua" },
  { code: "CI-192", nom: "Treichville" },
  { code: "CI-193", nom: "Vavoua" },
  { code: "CI-194", nom: "Worofla" },
  { code: "CI-195", nom: "Yakasse Attobrou" },
  { code: "CI-196", nom: "Yamoussoukro" },
  { code: "CI-197", nom: "Yopougon" },
  { code: "CI-198", nom: "Zikisso" },
  { code: "CI-199", nom: "Zouan Hounien" },
  { code: "CI-200", nom: "Zoukougbeu" },
  { code: "CI-201", nom: "Zuenoula" },
];

async function main() {
  console.log(`Import de ${COMMUNES.length} communes de Côte d'Ivoire (source : DGDDL — Ministère de l'Intérieur)\n`);
  let created = 0;
  let updated = 0;

  for (const c of COMMUNES) {
    const existing = await prisma.commune.findUnique({ where: { code: c.code } });
    await prisma.commune.upsert({
      where: { code: c.code },
      update: { nom: c.nom, isActive: true },
      create: { code: c.code, nom: c.nom, isActive: true },
    });
    if (existing) updated++;
    else created++;
  }

  console.log(`✔ ${created} créées, ${updated} déjà existantes (mises à jour).`);
}

main()
  .catch((e) => {
    console.error("Erreur durant l'import :", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
